/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/wellness`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app/+html`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app/wellness`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/src/PressableScale`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/src/StatusBarFake`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/src/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app${'/(tabs)'}/growth` | `/../frontend/app/growth`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app${'/(tabs)'}/index` | `/../frontend/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app${'/(tabs)'}/travel` | `/../frontend/app/travel`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cyber` | `/cyber`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/growth` | `/growth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/travel` | `/travel`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/wellness`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/app/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/app/+html`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/app/wellness`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/src/PressableScale`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/src/StatusBarFake`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/src/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/app${'/(tabs)'}/growth` | `/../frontend/app/growth`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/app${'/(tabs)'}/index` | `/../frontend/app/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/app${'/(tabs)'}/travel` | `/../frontend/app/travel`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cyber` | `/cyber`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/growth` | `/growth`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/travel` | `/travel`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/wellness${`?${string}` | `#${string}` | ''}` | `/../frontend/app/index${`?${string}` | `#${string}` | ''}` | `/../frontend/app/+html${`?${string}` | `#${string}` | ''}` | `/../frontend/app/wellness${`?${string}` | `#${string}` | ''}` | `/../frontend/src/PressableScale${`?${string}` | `#${string}` | ''}` | `/../frontend/src/StatusBarFake${`?${string}` | `#${string}` | ''}` | `/../frontend/src/theme${`?${string}` | `#${string}` | ''}` | `/../frontend/app${'/(tabs)'}/growth${`?${string}` | `#${string}` | ''}` | `/../frontend/app/growth${`?${string}` | `#${string}` | ''}` | `/../frontend/app${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/../frontend/app/index${`?${string}` | `#${string}` | ''}` | `/../frontend/app${'/(tabs)'}/travel${`?${string}` | `#${string}` | ''}` | `/../frontend/app/travel${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cyber${`?${string}` | `#${string}` | ''}` | `/cyber${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/growth${`?${string}` | `#${string}` | ''}` | `/growth${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/travel${`?${string}` | `#${string}` | ''}` | `/travel${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/wellness`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app/+html`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app/wellness`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/src/PressableScale`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/src/StatusBarFake`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/src/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app${'/(tabs)'}/growth` | `/../frontend/app/growth`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app${'/(tabs)'}/index` | `/../frontend/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/app${'/(tabs)'}/travel` | `/../frontend/app/travel`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cyber` | `/cyber`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/growth` | `/growth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/travel` | `/travel`; params?: Router.UnknownInputParams; };
    }
  }
}
